x-service: &service  
  image: oven/bun:1.2.15-alpine
  user: "${UID}:${GID}"
  working_dir: /home/bun/app
  volumes:
    - .:/home/bun/app
    - ~/.bun:/home/bun/.bun

services:
  front:
    <<: *service
    container_name: front
    command: sh -c "bun run start-dev & bun run live-reload & wait"
    env_file:
      - .env
    ports:
      - ${PORT}:${PORT}
      - ${LIVE_RELOAD_PORT}:${LIVE_RELOAD_PORT}
